export const GET_STATE = "GET_STATE"

export const GET_TOKEN_OAUTH2_SUCCESS = "GET_TOKEN_OAUTH2_SUCCESS";
export const GET_TOKEN_OAUTH2_FAILED = "GET_TOKEN_OAUTH2_FAILED";

export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_DATA_SUCCESS";
export const UPDATE_USER_DATA_FAILED = "UPDATE_USER_DATA_FAILED";